name: smart_alarm
description: A smart alarm clock application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^15.1.0+1
  just_audio: ^0.9.34
  vibration: ^1.8.3
  workmanager: ^0.5.1
  timezone: ^0.9.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
  
  fonts:
    - family: AlibabaPuHuiTi
      fonts:
        - asset: assets/fonts/AlibabaPuHuiTi-3-115-Black.ttf
          weight: 900 